package alice.tuprologx.runtime.corba;

/**
* org/alice/tuprologx/runtime/corba/PrologHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from org/alice/tuprologx/runtime/corba/Prolog.idl
* venerd? 28 dicembre 2001 12.37.09 GMT+01:00
*/

public final class PrologHolder implements org.omg.CORBA.portable.Streamable
{
  public Prolog value = null;

  public PrologHolder ()
  {
  }

  public PrologHolder (Prolog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PrologHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PrologHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PrologHelper.type ();
  }

}
